alias reload_zshrc!='. ~/.zshrc'
alias reload_i3!='i3-msg restart'
alias reload_tmux!='tmux source-file ~/.tmux.conf'
alias reload_Xresources!='xrdb ~/.Xresources'
alias reload_fonts!='fc-cache -vf ~/.fonts'
alias cpdir!='echo -e -n "$(pwd)" | xclip -in -selection clipboard'
alias m='man'
